scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile0`, function (sprite, location) {
    game.gameOver(true)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    myDart.throwDart()
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile`, function (sprite, location) {
    info.changeScoreBy(1)
    info.changeLifeBy(1)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    myDart.controlWithArrowKeys(true)
})
let myDart: Dart = null
Render.toggleViewMode()
Render.setViewMode(ViewMode.raycastingView)
let mySprite = sprites.create(img`
    . . . . 2 2 2 2 2 2 2 . . . . . 
    . . . . 2 4 4 4 4 4 2 2 2 . . . 
    . . . 2 2 4 4 4 4 4 4 4 2 2 . . 
    . . 2 2 4 4 4 4 4 4 4 4 4 2 2 . 
    . . 2 4 4 4 4 4 4 4 4 4 4 4 2 . 
    . 2 2 4 4 4 f 4 4 f 4 4 4 4 2 2 
    . 2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 
    2 2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 
    2 4 4 4 4 4 f 4 4 f 4 4 4 4 4 2 
    2 4 4 4 4 4 f f f f 4 4 4 4 4 2 
    2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 
    2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 
    2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 2 
    2 2 4 4 4 4 4 4 4 4 4 4 4 2 2 . 
    . 2 2 2 2 4 4 2 2 2 2 2 2 2 . . 
    . . . . 2 2 2 2 . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 100, 100)
scene.cameraFollowSprite(mySprite)
scene.setBackgroundImage(img`
    cccccccccccccccccccccccccccccccccddccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccdccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccdddcccccccccccdccccccccccccccccccccccccccccccccfccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccddbbdccccccc33333ccccccccccccccccccccccccccccccccfccccccccccccdccccccccccccccccccccccccccccccccccccccccccccccccffcccccccccccccccccccccccccccccccc
    ccccccccccccccdbbbbbddc3333ccdccccccccccccccccccccccdcccccccccccccccccccddccccfcccccccdccccccccccccccccccccccfcccccccccccccccccfcccccc3cccccfccccccccccccccccccc
    cccdddddddddddfbbbbbbbd3dddddcccccccccccccccccccccccdcccccccccdddccccdddfccccccccccccccc3ccccccccc33cccdcccccccccfccccccfcccccccccccc3fcccffcccccccccccccffccccc
    dccccccccccccfffbbffbbbbbfcfffccccccccccccccccccccccffcccccccccccdddddcccccccccccccccc3cc33ccc3ccccc33ccdccccccccffcfcccfccccddccccc3cfcccccccffcccccfcccccccccc
    cdcccccccccffccfffccffffffdccccccccccccccddccdcccccccccccccddddddddcfcddddcccccccccccccccc33333ccccccc333dccccccccccfccccddddddcccc3cccccccccccccccccdcccccccccc
    ccdccccccffcccccccccccccccdccccccccccccccccccdddccccccccccccccccccccfddcccdddcccccccccccccccccc33333ccccc3333cdddcccfddddddddccccc3cccccccccccccccffdfcfcccccccc
    ccdffccccfcccccccdcccccccccdccffffffffccccdddddddcccccccccddddccccc333cccccccdddcccc3fcccccccccccccc3333ccddd3333ddddddddcccccccc3cccccccccccccccccdd3333ccccccc
    cccdcffffccccccccdcccc3ccccdffccccccdddcccccfccccccccdccccccccc3333dccccccccccc3dddc3fcccccccccccccccccc33333ddd333333333ccccccc3cfccccccccccc3333333cf3ccccccfc
    ccccdccdddddcccccdcccc3cccccdccccdddccffffffcccccccddccccfc3333ddddcccccccccccc3ccc3dfcccfcccccccccccddddd33d3333dddddddd333333333333333333333dcccdccccfcddccccc
    cccccddccccccccccdcccc3ccccccdccdccccccccccdcccccccccccccddddddccccc33cccccccc3cc33ccddddddddddddddddddddddc33ddd3333ddcccccc33cccccc3ccccccdddccddccddddccccccc
    cccddcdccccdcccc3ddddd3ddddcccdccccdddccccdcccccccdddddddccccccccc33ccccccccccc333ccccd333ddcccccccddcdddcccddcccccdd33333c33ccccccccc333cddccdcdddddccccccccccc
    ccdccccddcccddccd3ddddc3ccccccdddddcccccddcccccccccc33cccddddddd33cccccccccc333ccc3333333333ddcccddddddcccddcccccddccccccc33ccccccccccccd3333333d3cccccccccccccc
    cccdcccccdddccdddc3ccccc3dddddcccddcccddcccccccccc33cccccccccc33ccdddddddd33ccccccccccccccccccdddddddccdddcccccddcccccccc3ccccccccccccdddddddccd3ccccccccccccccc
    ccccdcccccccddcddcc33ccccccccccccccdddccccccccc333ccccccccc333cccccccccc33ccdddddddddcccccccccdddddccddccccccddccccccccccccccccccccddddcddccdc33cccccccccccccccc
    cccccddccccccdcdcddcc3ccccccccccccddccddddddd33cccccccccc33ccccccccc3333dccccccccccccddddddddddccccddcdddddcccddccccccccccccccddddddccccccd333cccccccccccccccccc
    cccccccdccccccddcccddd33333cccccddcccccccccc3ccccddddd333ddddd333333cccdcccccdddcccccccccccccddddddddddccccccccdddddddddddddddccdcdc3333333ccccccccccccccccccccc
    ccccccccddcddddcccccccddddc33333333ccccccc33cccddc3333ccc33333cdccccccdcccdddccccccccccccccccddddcccccccccccccccdccccccccccccccdc333ccccccccccccccccddcccccccccc
    ccccccccccdddcccccccccccccdddcccccc3333333333333333333333cccccddcccccdccdddddddddddddccccccccdcccccccccccccccccccdcccccccccccddcccccccccccccccccddddcccccccccccc
    cccccccccccccdddddddddddddcccdddccccccccc33333cdcccccccccccccdcccccddcccccccccccccccccccccccccccccccccccccccccccccccccccccccdcccccccccccccccddddcccccccccccccccc
    ccccccccccccccccccccccccccccccccdddccdcccdcccccdcccccccccccddccccddccccccccccccccccccccccccccccccccccccccccccccccccccccccccdccccccccccccddddcccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccddddddcccccccdcccccccccdddddddcccccccccccccccccccccccccccccccccccccccccccccccccccccccccdccccccccdddddcccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccdcdcdddddddddcccccccccddddcdddddccccccccccccccccccccccccccccccccccccccccccccccccccccdcccddddddccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccdcccccccccccddddddddddddddddddccccccccccccccccccccccccccccccccccccccccccccccccccccdddddccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccaccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaaaaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffccccccccccccccccccccccccccccccccccccccccccccacccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffccccccccccccccccccccccccccccccccccaaccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffcccffffffffcccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccffffffcccccccccccccccccccccccccccccccccccccccccccccaaacccccccccccccccccccccccccccffffffffffffccccffffffffcccccccccccccccccccccccccccccccccccccccc
    cccccaacccccccfffffffcccccccfffffcccccffffffcaccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffcccccffffffffccccfffffffccccccccccccccccccccccccccccc
    ccccccccccccccffffffccccccccfffffcccccffffffccaaaaafffccccccccccccccccccccccccccccccccccccccccccffffffffffcccccffffffffcccccfffffffccccccffffccccccccccccccccccc
    ccccccccccccccffffffcccccccffffffccccfffffffccccffffffccccccccccccccccccccccccccccccccccccccccccfffffffffcccccfffffffffcccccfffffffccccffffffffccccccccccccccccc
    ccccccccccccccfffffccccccccffffffccccfffffffcccfffffffccccccccccccccccccccccccccccccccccccccccccffffffffccccccffffffffcccccffffffffccccffffffffcccaccccccccccccc
    ccccccccccccccfffffcccccccffffffcccccffffffccccfffffffccccccccccccccccccccccccccccccccccccccccccffffffffcccccffffffffccccccfffffffccccfffffffffcccaccccccccccccc
    ccacccccccccccffffffffccccfffffffffffffffffcccfffffffffcccccccccccccccccccccccccccccccccccccccccfffffffffccccffffffffccccccffffffcccccfffffffffcccaccccccccccccc
    ccccccccccccccfffffffffffcfffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffcccccccfffffccccccfffffffffccccacccccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccacccccccccccccccccccccccccccccfffffffffffffffffffffffccccfffffffccccfffffffffccccacccccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccaccccacccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffcccccaccccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccccacccccccccccccaccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccacccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccacccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccacccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccccccaccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffccccccccaccccccccc
    ccccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccccccaccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    ccccccccccccccffffffffffffffffffffffffffffffffffffffffccccccccccccccccacccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    ccccccccccccccffffffffffffffffffffffffffffffffffffffffcccccccccccccccccaccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    ccccccccccccccffffffffffffffffffffffffffffffffffffffffccccccccccccccccccaaccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccaccccccccffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccacccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccacccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccaaccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccacccccccfffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccaacccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccacccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccacccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccacccccccccccccaccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccacccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffccccccccccaccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffffcccccccccccacccccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccacccccc
    ccccccacccccffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccccccccccacccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccacccccc
    ccccccacccccfffffffffffffffffffffffffffffffffaafffffffccccccccccccccccccccccccccccccacccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccc
    ccccccacccccfffffffffffffffffffffffffffffaaaafffffffffccccccccccccccccccccccccccccccacccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccc
    ccccccacccccffffffffffffffffffffffffaaaaaffafffffffaffccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccc
    ccccccccccccfffffffffffffffffffaaaaafffffffafffffaafffccccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccc
    ccccccccccccfffffffffffffaaaaaafffffffffffaffffaaffffffcccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccc
    cccccaccccccfffffffffffffffffffffffffffffafffaaffffffffcccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccc
    ccccccccccccffffffffffffffffffffffffffffaffaaffffffffffcccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccc
    ccccccccccccffffffffffffffffffffffffffffaaaffffffffffffccccccccccccccccccccccccccccccccccccccccccffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    cccccaccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    ccaaacccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    ccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    ccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    ccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccaaccccccccccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccaaacccccccc
    ccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccacccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccc
    cccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccc
    cccccccccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccc
    ccccccccccccfaaaaaaaaafffffffffffffffffffffffffffffffffffffffffffffffff5555555ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccccccccccc
    cccccccccccffaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffffffff5555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccc
    cccccccccccfaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffffff5555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccc
    ccccccccccfaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffffff55555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccc
    cccccccccfaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffffffff55555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccc
    cccccccffaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffffffff55555555fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccccccccccccccccccccccc
    cfffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffff555555555fffffffffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaffccccccccccccccccccccc
    ffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffff555555555fffffffffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaafffffcccccccccccccccc
    aaffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffff5555555555fffffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaffcccccccccccccc
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaff55555555ffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffccccccccc
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffff555555fffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffcccccccc
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffff55555ffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffccccc
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffff55fffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffff
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffaffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffaaaffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaafffffffffffffffffffffffffffffaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    `)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnTile(mySprite, tiles.getTileLocation(0, 28))
myDart = darts.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .......22...22......
    ......2322.2222.....
    ......232222222.....
    ......222222222.....
    .......22222b2......
    ........222b2.......
    .........222........
    ..........2.........
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Projectile, 10, 110)
info.setScore(1200)
game.onUpdateInterval(500, function () {
    info.changeScoreBy(-1)
})
